apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app.kubernetes.io/name: lavinmq-operator
    app.kubernetes.io/managed-by: EtcdController
spec:
  clusterIP: None  # This makes it a headless service
  ports:
    - name: client
      port: 2379
      targetPort: 2379
      protocol: TCP
    - name: peer
      port: 2380
      targetPort: 2380
      protocol: TCP
  selector:
    app.kubernetes.io/name: lavinmq-operator
    app.kubernetes.io/managed-by: EtcdController 