# permissions for end users to view etcds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-sdk
    app.kubernetes.io/managed-by: kustomize
  name: etcd-viewer-role
rules:
- apiGroups:
  - cloudamqp.com.cloudamqp.com
  resources:
  - etcds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudamqp.com.cloudamqp.com
  resources:
  - etcds/status
  verbs:
  - get
