---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloudamqp.com.cloudamqp.com
  resources:
  - etcds
  - lavinmqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudamqp.com.cloudamqp.com
  resources:
  - etcds/finalizers
  - lavinmqs/finalizers
  verbs:
  - update
- apiGroups:
  - cloudamqp.com.cloudamqp.com
  resources:
  - etcds/status
  - lavinmqs/status
  verbs:
  - get
  - patch
  - update
