apiVersion: cloudamqp.com.cloudamqp.com/v1alpha1
kind: Etcd
metadata:
  labels:
    app.kubernetes.io/name: operator-sdk
    app.kubernetes.io/managed-by: kustomize
    app: etcd-sample
  name: etcd-sample
spec:
  replicas: 1
  dataVolumeClaim:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi