apiVersion: cloudamqp.com.cloudamqp.com/v1alpha1
kind: LavinMQ
metadata:
  labels:
    app.kubernetes.io/name: operator-sdk
    app.kubernetes.io/managed-by: kustomize
    app: lavinmq-sample
  name: lavinmq-sample
spec:
  image: cloudamqp/lavinmq:2.2.0
  replicas: 1
  ports:
    - containerPort: 15672
      name: http
    - containerPort: 5672
      name: amqp
    - containerPort: 15671
      name: https
    - containerPort: 5671
      name: amqps
  etcdEndpoints:
    - etcd-cluster-0.etcd-cluster.default.svc.cluster.local:2379
    - etcd-cluster-1.etcd-cluster.default.svc.cluster.local:2379
    - etcd-cluster-2.etcd-cluster.default.svc.cluster.local:2379
  tlsSecret:
    name: lavinmq-tls
  dataVolumeClaim:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
  config:
    consumer_timeout: 20000

