name: Build Docker Image on Tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          make docker-buildx build-installer
        env:
          IMG: ghcr.io/${{ github.repository_owner }}/lavinmq-operator:${{ github.ref_name }}

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: dist/install.yaml
          path: dist/install.yaml
